[package]
name = "lxh-state"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
lxh-core = { workspace = true }
async-trait = { workspace = true }
image = { workspace = true }
atspi = { workspace = true }
tokio = { workspace = true }
x11rb = { version = "0.13" }
