[package]
name = "lxs-action"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
lxs-core = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
x11rb = { workspace = true }
x11-keysymdef = { workspace = true }
arboard = { version = "3", default-features = false }
