[package]
name = "lxs-state"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
lxs-core = { workspace = true }
async-trait = { workspace = true }
x11 = { workspace = true }
image = { workspace = true }
atspi = { workspace = true }
tokio = { workspace = true }
